# Generated by Django 3.2.8 on 2023-03-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211012_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='placed',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='placed'),
        ),
    ]
