# Generated by Django 3.2.8 on 2023-03-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_user_placed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='placed',
        ),
        migrations.AddField(
            model_name='student',
            name='placed',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='placed'),
        ),
    ]
