# Generated by Django 3.2.8 on 2023-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_student_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='company',
            field=models.CharField(max_length=100, null=True, verbose_name='company'),
        ),
    ]
