# Generated by Django 3.2.8 on 2023-03-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='unit',
            new_name='classname',
        ),
    ]
