# Generated by Django 3.2.8 on 2023-03-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_rename_unit_classroom_classname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='classname',
            new_name='branch',
        ),
    ]
