# Generated by Django 3.2.8 on 2023-03-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_alter_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomstream',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='<str:id>/create/stream'),
        ),
    ]
