# Generated by Django 3.2.8 on 2023-03-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0011_roomstream_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstream',
            name='file',
            field=models.FileField(null=True, upload_to='stream/'),
        ),
    ]
