# Generated by Django 3.2.8 on 2023-03-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_roomstream_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomstream',
            name='file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
